<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Aritz Adin y Jaione Etxeberria">

<title>BIOEST 2023-24 - Práctica 3: Contrastes de hipótesis paramétricos y análisis de la varianza</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">BIOEST 2023-24</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Programa</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Practica0.html" rel="" target="">
 <span class="menu-text">Práctica 0</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Practica1.html" rel="" target="">
 <span class="menu-text">Práctica 1</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Practica2.html" rel="" target="">
 <span class="menu-text">Práctica 2</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./Practica3.html" rel="" target="" aria-current="page">
 <span class="menu-text">Práctica 3</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Practica4.html" rel="" target="">
 <span class="menu-text">Práctica 4</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#descripción" id="toc-descripción" class="nav-link active" data-scroll-target="#descripción">Descripción</a></li>
  <li><a href="#contraste-paramétricos" id="toc-contraste-paramétricos" class="nav-link" data-scroll-target="#contraste-paramétricos">1. Contraste paramétricos</a>
  <ul class="collapse">
  <li><a href="#contrasta-al-nivel-de-significación-alpha0.05-si-el-nivel-medio-de-colesterol-en-los-hombres-del-condado-de-buckingham-es-superior-a-200mgdl.-justifica-si-puedes-asumir-normalidad." id="toc-contrasta-al-nivel-de-significación-alpha0.05-si-el-nivel-medio-de-colesterol-en-los-hombres-del-condado-de-buckingham-es-superior-a-200mgdl.-justifica-si-puedes-asumir-normalidad." class="nav-link" data-scroll-target="#contrasta-al-nivel-de-significación-alpha0.05-si-el-nivel-medio-de-colesterol-en-los-hombres-del-condado-de-buckingham-es-superior-a-200mgdl.-justifica-si-puedes-asumir-normalidad.">1.1. Contrasta al nivel de significación <span class="math inline">\(\alpha=0.05\)</span> si el nivel medio de colesterol en los hombres del condado de Buckingham es superior a 200mg/dL. Justifica si puedes asumir normalidad.</a></li>
  <li><a href="#calcula-la-potencia-del-contraste-anterior-si-el-verdadero-nivel-medio-de-colesterol-en-los-hombres-del-condado-de-buckingham-es-210-mgdl.-cuantas-observaciones-necesitarías-en-tu-muestra-para-obtener-una-potencia-de-0.9" id="toc-calcula-la-potencia-del-contraste-anterior-si-el-verdadero-nivel-medio-de-colesterol-en-los-hombres-del-condado-de-buckingham-es-210-mgdl.-cuantas-observaciones-necesitarías-en-tu-muestra-para-obtener-una-potencia-de-0.9" class="nav-link" data-scroll-target="#calcula-la-potencia-del-contraste-anterior-si-el-verdadero-nivel-medio-de-colesterol-en-los-hombres-del-condado-de-buckingham-es-210-mgdl.-cuantas-observaciones-necesitarías-en-tu-muestra-para-obtener-una-potencia-de-0.9">1.2. Calcula la potencia del contraste anterior si el verdadero nivel medio de colesterol en los hombres del condado de Buckingham es 210 mg/dL. ¿Cuantas observaciones necesitarías en tu muestra para obtener una potencia de 0.9?</a></li>
  <li><a href="#contrasta-al-nivel-de-significación-alpha0.10-si-la-presión-diastólica-media-de-los-hombres-es-distinta-a-la-presión-diastólica-media-de-las-mujeres." id="toc-contrasta-al-nivel-de-significación-alpha0.10-si-la-presión-diastólica-media-de-los-hombres-es-distinta-a-la-presión-diastólica-media-de-las-mujeres." class="nav-link" data-scroll-target="#contrasta-al-nivel-de-significación-alpha0.10-si-la-presión-diastólica-media-de-los-hombres-es-distinta-a-la-presión-diastólica-media-de-las-mujeres.">1.3. Contrasta al nivel de significación <span class="math inline">\(\alpha=0.10\)</span>, si la presión diastólica media de los hombres es distinta a la presión diastólica media de las mujeres.</a></li>
  <li><a href="#se-dispone-de-dos-aparatos-uno-nuevo-y-otro-antiguo-para-medir-los-niveles-de-glucosa-en-sangre.-los-médicos-sospechan-que-el-nuevo-aparato-proporciona-niveles-de-glucosa-en-sangre-superiores-al-antiguo.-se-dispone-de-una-muestra-con-15-pacientes-diabéticos-a-los-que-se-les-ha-medido-los-niveles-de-glucosa-con-los-dos-aparatos.-las-medidas-se-encuentran-en-el-fichero-glucose-de-la-librería-paswr2." id="toc-se-dispone-de-dos-aparatos-uno-nuevo-y-otro-antiguo-para-medir-los-niveles-de-glucosa-en-sangre.-los-médicos-sospechan-que-el-nuevo-aparato-proporciona-niveles-de-glucosa-en-sangre-superiores-al-antiguo.-se-dispone-de-una-muestra-con-15-pacientes-diabéticos-a-los-que-se-les-ha-medido-los-niveles-de-glucosa-con-los-dos-aparatos.-las-medidas-se-encuentran-en-el-fichero-glucose-de-la-librería-paswr2." class="nav-link" data-scroll-target="#se-dispone-de-dos-aparatos-uno-nuevo-y-otro-antiguo-para-medir-los-niveles-de-glucosa-en-sangre.-los-médicos-sospechan-que-el-nuevo-aparato-proporciona-niveles-de-glucosa-en-sangre-superiores-al-antiguo.-se-dispone-de-una-muestra-con-15-pacientes-diabéticos-a-los-que-se-les-ha-medido-los-niveles-de-glucosa-con-los-dos-aparatos.-las-medidas-se-encuentran-en-el-fichero-glucose-de-la-librería-paswr2.">1.4. Se dispone de dos aparatos, uno nuevo y otro antiguo, para medir los niveles de glucosa en sangre. Los médicos sospechan que el nuevo aparato proporciona niveles de glucosa en sangre superiores al antiguo. Se dispone de una muestra con 15 pacientes diabéticos a los que se les ha medido los niveles de glucosa con los dos aparatos. Las medidas se encuentran en el fichero <code>GLUCOSE</code> de la librería <code>PASWR2</code>.</a></li>
  <li><a href="#contrasta-al-nivel-de-significación-alpha0.05-si-la-proporción-de-hombres-con-hemoglobina-glicosilada-glyhb-por-encima-del-6-es-superior-a-0.2." id="toc-contrasta-al-nivel-de-significación-alpha0.05-si-la-proporción-de-hombres-con-hemoglobina-glicosilada-glyhb-por-encima-del-6-es-superior-a-0.2." class="nav-link" data-scroll-target="#contrasta-al-nivel-de-significación-alpha0.05-si-la-proporción-de-hombres-con-hemoglobina-glicosilada-glyhb-por-encima-del-6-es-superior-a-0.2.">1.5. Contrasta al nivel de significación <span class="math inline">\(\alpha=0.05\)</span> si la proporción de hombres con hemoglobina glicosilada (<code>glyhb</code>) por encima del 6% es superior a 0.2.</a></li>
  <li><a href="#contrasta-al-nivel-de-significación-alpha0.05-si-la-proporción-de-hombres-con-colesterol-por-debajo-de-200mgdl-es-superior-a-la-proporción-de-mujeres-con-colesterol-por-debajo-de-200mgdl." id="toc-contrasta-al-nivel-de-significación-alpha0.05-si-la-proporción-de-hombres-con-colesterol-por-debajo-de-200mgdl-es-superior-a-la-proporción-de-mujeres-con-colesterol-por-debajo-de-200mgdl." class="nav-link" data-scroll-target="#contrasta-al-nivel-de-significación-alpha0.05-si-la-proporción-de-hombres-con-colesterol-por-debajo-de-200mgdl-es-superior-a-la-proporción-de-mujeres-con-colesterol-por-debajo-de-200mgdl.">1.6. Contrasta al nivel de significación <span class="math inline">\(\alpha=0.05\)</span> si la proporción de hombres con colesterol por debajo de 200mg/dL es superior a la proporción de mujeres con colesterol por debajo de 200mg/dL.</a></li>
  </ul></li>
  <li><a href="#análisis-de-la-varianza" id="toc-análisis-de-la-varianza" class="nav-link" data-scroll-target="#análisis-de-la-varianza">2. Análisis de la varianza</a>
  <ul class="collapse">
  <li><a href="#contrasta-al-nivel-de-significación-alpha0.10-si-el-tamaño-del-cuerpo-frame-influye-en-la-presión-diastólica-bp.1d-de-las-mujeres." id="toc-contrasta-al-nivel-de-significación-alpha0.10-si-el-tamaño-del-cuerpo-frame-influye-en-la-presión-diastólica-bp.1d-de-las-mujeres." class="nav-link" data-scroll-target="#contrasta-al-nivel-de-significación-alpha0.10-si-el-tamaño-del-cuerpo-frame-influye-en-la-presión-diastólica-bp.1d-de-las-mujeres.">2.1. Contrasta al nivel de significación <span class="math inline">\(\alpha=0.10\)</span> si el tamaño del cuerpo (<code>frame</code>) influye en la presión diastólica (<code>bp.1d</code>) de las mujeres.</a></li>
  </ul></li>
  <li><a href="#para-entregar" id="toc-para-entregar" class="nav-link" data-scroll-target="#para-entregar">3. Para entregar</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Práctica 3: Contrastes de hipótesis paramétricos y análisis de la varianza</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Aritz Adin y Jaione Etxeberria </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">31/10/2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="descripción" class="level1">
<h1>Descripción</h1>
<p>En esta práctica vamos a trabajar con el fichero de datos <code>diabetes</code>.</p>
<ul>
<li><p>El fichero de datos contiene 19 variables medidas sobre 403 pacientes. Estos pacientes forman parte de un estudio con 1046 sujetos diseñado para investigar la prevalencia de la de obesidad, diabetes, y otros factores de riesgo cardiovasculares para Afroamericanos en Virginia, EEUU.</p></li>
<li><p>Según Dr John Hong, Diabetes Mellitus Tipo II está asociada con la obesidad. El índice cintura-cadera puede ser un predictor en diabetes y enfermedades de corazón.</p></li>
<li><p>Diabetes Mellitus Tipo II está también asociada con hipertensión y ambos pueden ser parte del <em>“Síndrome X”</em>.</p></li>
<li><p>Los 403 sujetos del estudio son aquellos a los que se les hizo un seguimiento de diabetes. La hemoglobina glicosilada &gt;7.0 se toma normalmente como diagnóstico positivo de diabetes.</p></li>
</ul>
<p>El fichero original puede descargarse de la web: <a href="http://biostat.mc.vanderbilt.edu/wiki/Main/DataSets" class="uri">http://biostat.mc.vanderbilt.edu/wiki/Main/DataSets</a></p>
<p>Para más información ver el paper: Willems JP, Saunders JT, DE Hunt, JB Schorling. <em>Prevalence of coronary heart disease risk factors among rural blacks: A community-based study</em>. Southern Medical Journal 90: 814-820; 1997. <a href="https://europepmc.org/abstract/med/9258308" class="uri">https://europepmc.org/abstract/med/9258308</a></p>
<p>Estas son las variables que contiene el fichero (se han eliminado alguna del fichero original y se han reemplazado algunos valores perdidos):</p>
<table class="table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Descripción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>id</td>
<td>Subject ID</td>
</tr>
<tr class="even">
<td>chol</td>
<td>Total Cholesterol (mg/dL)</td>
</tr>
<tr class="odd">
<td>stab.glu</td>
<td>Stabilized Glucose (mg/dL)</td>
</tr>
<tr class="even">
<td>hdl</td>
<td>High Density Lipoprotein (mg/dL)</td>
</tr>
<tr class="odd">
<td>ratio</td>
<td>Cholesterol/HDL Ratio</td>
</tr>
<tr class="even">
<td>glyhb</td>
<td>Glycosolated Hemoglobin (%)</td>
</tr>
<tr class="odd">
<td>location</td>
<td>Buckingham or Louisa</td>
</tr>
<tr class="even">
<td>age</td>
<td>Age of patient (years)</td>
</tr>
<tr class="odd">
<td>gender</td>
<td>Male or Female</td>
</tr>
<tr class="even">
<td>height</td>
<td>Height (inches)</td>
</tr>
<tr class="odd">
<td>weight</td>
<td>Weight (pounds)</td>
</tr>
<tr class="even">
<td>frame</td>
<td>Body frame size (small, medium, large)</td>
</tr>
<tr class="odd">
<td>bp.1s</td>
<td>First Systolic Blood Pressure (mmHg)</td>
</tr>
<tr class="even">
<td>bp.1d</td>
<td>First Diastolic Blood Pressure (mmHg)</td>
</tr>
<tr class="odd">
<td>waist</td>
<td>Waistline (inches)</td>
</tr>
<tr class="even">
<td>hip</td>
<td>Hip measurement (inches)</td>
</tr>
</tbody>
</table>
<p>En primer lugar, cargamos la librería <code>PASWR2</code> y leemos el fichero <code>diabetes</code> en R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(PASWR2)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>diabetes <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"diabetes.txt"</span>, <span class="at">header=</span><span class="cn">TRUE</span>, <span class="at">sep=</span><span class="st">""</span>, <span class="at">dec=</span><span class="st">"."</span>, <span class="at">stringsAsFactors=</span><span class="cn">TRUE</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(diabetes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    id chol stab.glu hdl ratio glyhb   location age gender height weight  frame
1 1000  203       82  56   3.6  4.31 Buckingham  46 female     62    121 medium
2 1001  165       97  24   6.9  4.44 Buckingham  29 female     64    218  large
3 1002  228       92  37   6.2  4.64 Buckingham  58 female     61    256  large
4 1003   78       93  12   6.5  4.63 Buckingham  67   male     67    119  large
5 1005  249       90  28   8.9  7.72 Buckingham  64   male     68    183 medium
6 1008  248       94  69   3.6  4.81 Buckingham  34   male     71    190  large
  bp.1s bp.1d waist hip
1   118    59    29  38
2   112    68    46  48
3   190    92    49  57
4   110    50    33  38
5   138    80    44  41
6   132    86    36  42</code></pre>
</div>
</div>
</section>
<section id="contraste-paramétricos" class="level1">
<h1>1. Contraste paramétricos</h1>
<section id="contrasta-al-nivel-de-significación-alpha0.05-si-el-nivel-medio-de-colesterol-en-los-hombres-del-condado-de-buckingham-es-superior-a-200mgdl.-justifica-si-puedes-asumir-normalidad." class="level3">
<h3 class="anchored" data-anchor-id="contrasta-al-nivel-de-significación-alpha0.05-si-el-nivel-medio-de-colesterol-en-los-hombres-del-condado-de-buckingham-es-superior-a-200mgdl.-justifica-si-puedes-asumir-normalidad.">1.1. Contrasta al nivel de significación <span class="math inline">\(\alpha=0.05\)</span> si el nivel medio de colesterol en los hombres del condado de Buckingham es superior a 200mg/dL. Justifica si puedes asumir normalidad.</h3>
<p>Defimos la variable <span class="math display">\[X=\mbox{"Nivel de colesterol (mg/dL) en los hombres del condado de Buckingham"}\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Seleccionamos los datos ##</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>pos <span class="ot">&lt;-</span> <span class="fu">which</span>(diabetes<span class="sc">$</span>gender<span class="sc">==</span><span class="st">"male"</span> <span class="sc">&amp;</span> diabetes<span class="sc">$</span>location<span class="sc">==</span><span class="st">"Buckingham"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>chol.manB <span class="ot">&lt;-</span> diabetes<span class="sc">$</span>chol[pos]  </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Comprobamos la condición de normalidad ##</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">eda</span>(chol.manB)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Practica3_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Size (n)  Missing  Minimum   1st Qu     Mean   Median   TrMean   3rd Qu 
  86.000    0.000   78.000  174.000  203.603  197.500  202.536  230.750 
     Max    Stdev      Var  SE Mean   I.Q.R.    Range Kurtosis Skewness 
 347.000   44.598 1988.956    4.809   56.750  269.000    0.677    0.402 
SW p-val 
   0.208 </code></pre>
</div>
</div>
<p>Realizamos el contraste de hipótesis (<span class="math inline">\(\alpha=0.05\)</span>) <span class="math display">\[\begin{eqnarray*}
H_0: \, \mu=200 \\
H_1: \, \mu&gt;200 \\
\end{eqnarray*}\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(chol.manB, <span class="at">mu=</span><span class="dv">200</span>, <span class="at">conf.level=</span><span class="fl">0.95</span>, <span class="at">alternative=</span><span class="st">"greater"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  chol.manB
t = 0.74918, df = 85, p-value = 0.2279
alternative hypothesis: true mean is greater than 200
95 percent confidence interval:
 195.6054      Inf
sample estimates:
mean of x 
 203.6029 </code></pre>
</div>
</div>
<p><strong>Interpretación</strong>: Como el p-valor=0.228<span class="math inline">\(&gt; \alpha=0.05 \Rightarrow\)</span> No rechazar <span class="math inline">\(H_0\)</span>.</p>
<p>Es decir, con un nivel de significación de 5%, no podemos afirmar que el nivel medio de colesterol en los hombres del condado de Buckingham es superior a 200mg/dL.</p>
</section>
<section id="calcula-la-potencia-del-contraste-anterior-si-el-verdadero-nivel-medio-de-colesterol-en-los-hombres-del-condado-de-buckingham-es-210-mgdl.-cuantas-observaciones-necesitarías-en-tu-muestra-para-obtener-una-potencia-de-0.9" class="level3">
<h3 class="anchored" data-anchor-id="calcula-la-potencia-del-contraste-anterior-si-el-verdadero-nivel-medio-de-colesterol-en-los-hombres-del-condado-de-buckingham-es-210-mgdl.-cuantas-observaciones-necesitarías-en-tu-muestra-para-obtener-una-potencia-de-0.9">1.2. Calcula la potencia del contraste anterior si el verdadero nivel medio de colesterol en los hombres del condado de Buckingham es 210 mg/dL. ¿Cuantas observaciones necesitarías en tu muestra para obtener una potencia de 0.9?</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">power.t.test</span>(<span class="at">n=</span><span class="fu">length</span>(chol.manB), <span class="at">delta=</span><span class="dv">210-200</span>, <span class="at">sd=</span><span class="fu">sd</span>(chol.manB),</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">sig.level=</span><span class="fl">0.05</span>, <span class="at">type=</span><span class="st">"one.sample"</span>, <span class="at">alternative=</span><span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     One-sample t test power calculation 

              n = 86
          delta = 10
             sd = 44.59771
      sig.level = 0.05
          power = 0.5382013
    alternative = two.sided</code></pre>
</div>
</div>
<p><strong>Interpretación</strong>: Si el verdadero nivel medio de colesterol en los hombres del condado de Buckingham es 210 mg/dL, la probabilidad de rechazar la hipótesis nula en el test anterior (<span class="math inline">\(H1: \, \mu&gt;200\)</span>) es de 0.538.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">power.t.test</span>(<span class="at">power=</span><span class="fl">0.9</span>, <span class="at">delta=</span><span class="dv">210-200</span>, <span class="at">sd=</span><span class="fu">sd</span>(chol.manB),</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">sig.level=</span><span class="fl">0.05</span>, <span class="at">type=</span><span class="st">"one.sample"</span>, <span class="at">alternative=</span><span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     One-sample t test power calculation 

              n = 210.9181
          delta = 10
             sd = 44.59771
      sig.level = 0.05
          power = 0.9
    alternative = two.sided</code></pre>
</div>
</div>
<p><strong>Interpretación</strong>: Si el verdadero nivel medio de colesterol en los hombres del condado de Buckingham es 210 mg/dL, el tamaño de muestra necesario para obtener una potencia de 0.9 en el test anterior es <span class="math inline">\(n \geq 211\)</span>.</p>
</section>
<section id="contrasta-al-nivel-de-significación-alpha0.10-si-la-presión-diastólica-media-de-los-hombres-es-distinta-a-la-presión-diastólica-media-de-las-mujeres." class="level3">
<h3 class="anchored" data-anchor-id="contrasta-al-nivel-de-significación-alpha0.10-si-la-presión-diastólica-media-de-los-hombres-es-distinta-a-la-presión-diastólica-media-de-las-mujeres.">1.3. Contrasta al nivel de significación <span class="math inline">\(\alpha=0.10\)</span>, si la presión diastólica media de los hombres es distinta a la presión diastólica media de las mujeres.</h3>
<p>Definimos las variables <span class="math display">\[X=\mbox{"Presión diastólica (mmHg) de los hombres"}\]</span> <span class="math display">\[Y=\mbox{"Presión diastólica (mmHg) de la mujeres"}\]</span></p>
<ul>
<li>Comprueba que las dos muestras provienen de poblaciones normales.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Seleccionamos los datos de los hombres ##</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>pos1 <span class="ot">&lt;-</span> <span class="fu">which</span>(diabetes<span class="sc">$</span>gender<span class="sc">==</span><span class="st">"male"</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>bp1d.male <span class="ot">&lt;-</span> diabetes<span class="sc">$</span>bp<span class="fl">.1</span>d[pos1]</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">eda</span>(bp1d.male)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Practica3_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Size (n)  Missing  Minimum   1st Qu     Mean   Median   TrMean   3rd Qu 
 169.000    0.000   50.000   76.000   84.465   82.000   84.200   92.000 
     Max    Stdev      Var  SE Mean   I.Q.R.    Range Kurtosis Skewness 
 122.000   13.504  182.347    1.039   16.000   72.000    0.124    0.351 
SW p-val 
   0.058 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Seleccionamos los datos de las mujeres ##</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>pos2 <span class="ot">&lt;-</span> <span class="fu">which</span>(diabetes<span class="sc">$</span>gender<span class="sc">==</span><span class="st">"female"</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>bp1d.female <span class="ot">&lt;-</span>diabetes<span class="sc">$</span>bp<span class="fl">.1</span>d[pos2]</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">eda</span>(bp1d.female)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Practica3_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Size (n)  Missing  Minimum   1st Qu     Mean   Median   TrMean   3rd Qu 
 234.000    0.000   48.000   72.000   82.496   82.000   82.269   90.000 
     Max    Stdev      Var  SE Mean   I.Q.R.    Range Kurtosis Skewness 
 124.000   13.474  181.535    0.881   18.000   76.000   -0.014    0.216 
SW p-val 
   0.232 </code></pre>
</div>
</div>
<ul>
<li>¿Podemos asumir que las varianzas son iguales?</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Gráfico exploratorio ##</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(bp<span class="fl">.1</span>d <span class="sc">~</span> gender, <span class="at">data=</span>diabetes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Practica3_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Test para la igualdad de varianzas ##</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">var.test</span>(bp1d.male, bp1d.female, <span class="at">ratio=</span><span class="dv">1</span>, <span class="at">alternative=</span><span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    F test to compare two variances

data:  bp1d.male and bp1d.female
F = 1.0045, num df = 168, denom df = 233, p-value = 0.969
alternative hypothesis: true ratio of variances is not equal to 1
95 percent confidence interval:
 0.7605823 1.3352151
sample estimates:
ratio of variances 
          1.004471 </code></pre>
</div>
</div>
<p>Como p-valor=0.969&gt;0.05, no podemos rechazar la hipótesis nula de igualdad de varianzas.</p>
<ul>
<li>Realiza el correspondiente test de medias. <span class="math display">\[\begin{eqnarray*}
H_0: \, \mu_X-\mu_Y=0 \\
H_1: \, \mu_X-\mu_Y \neq 0 \\
\end{eqnarray*}\]</span></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(bp1d.male, bp1d.female, <span class="at">mu=</span><span class="dv">0</span>, <span class="at">var.equal=</span><span class="cn">TRUE</span>, <span class="at">alternative=</span><span class="st">"two.sided"</span>, <span class="at">conf.level=</span><span class="fl">0.9</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  bp1d.male and bp1d.female
t = 1.4469, df = 401, p-value = 0.1487
alternative hypothesis: true difference in means is not equal to 0
90 percent confidence interval:
 -0.2747344  4.2142710
sample estimates:
mean of x mean of y 
 84.46534  82.49558 </code></pre>
</div>
</div>
<p><strong>Interpretación</strong>: Como el p-valor=0.149<span class="math inline">\(&gt; \alpha=0.10 \Rightarrow\)</span> No rechazar <span class="math inline">\(H_0\)</span>.</p>
<p>Es decir, con un nivel de significación de 10%, no podemos afirmar que la presión diastólica media de los hombres sea distinta a la presión diastólica media de las mujeres.</p>
</section>
<section id="se-dispone-de-dos-aparatos-uno-nuevo-y-otro-antiguo-para-medir-los-niveles-de-glucosa-en-sangre.-los-médicos-sospechan-que-el-nuevo-aparato-proporciona-niveles-de-glucosa-en-sangre-superiores-al-antiguo.-se-dispone-de-una-muestra-con-15-pacientes-diabéticos-a-los-que-se-les-ha-medido-los-niveles-de-glucosa-con-los-dos-aparatos.-las-medidas-se-encuentran-en-el-fichero-glucose-de-la-librería-paswr2." class="level3">
<h3 class="anchored" data-anchor-id="se-dispone-de-dos-aparatos-uno-nuevo-y-otro-antiguo-para-medir-los-niveles-de-glucosa-en-sangre.-los-médicos-sospechan-que-el-nuevo-aparato-proporciona-niveles-de-glucosa-en-sangre-superiores-al-antiguo.-se-dispone-de-una-muestra-con-15-pacientes-diabéticos-a-los-que-se-les-ha-medido-los-niveles-de-glucosa-con-los-dos-aparatos.-las-medidas-se-encuentran-en-el-fichero-glucose-de-la-librería-paswr2.">1.4. Se dispone de dos aparatos, uno nuevo y otro antiguo, para medir los niveles de glucosa en sangre. Los médicos sospechan que el nuevo aparato proporciona niveles de glucosa en sangre superiores al antiguo. Se dispone de una muestra con 15 pacientes diabéticos a los que se les ha medido los niveles de glucosa con los dos aparatos. Las medidas se encuentran en el fichero <code>GLUCOSE</code> de la librería <code>PASWR2</code>.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Cargamos los datos ##</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(GLUCOSE)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(GLUCOSE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   patient    old    new
1        1 182.47 195.64
2        2 175.53 196.31
3        3 181.71 190.33
4        4 179.03 192.90
5        5 177.28 193.24
6        6 177.49 193.05
7        7 179.54 193.87
8        8 185.12 196.39
9        9 179.04 195.25
10      10 180.50 194.48
11      11 182.15 197.33
12      12 183.55 193.81
13      13 180.86 198.03
14      14 180.82 193.31
15      15 178.88 198.43</code></pre>
</div>
</div>
<ul>
<li>¿Son las muestras independientes?</li>
</ul>
<p>Sean <span class="math display">\[X=\mbox{"Nivel de glucosa (mg/dL) en sangre con el aparato nuevo"}\]</span> <span class="math display">\[Y=\mbox{"Nivel de glucosa (mg/dL) en sangre con el aparato viejo"}\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Las muestras NO son independientes (mismos individuos) ##</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> GLUCOSE<span class="sc">$</span>new <span class="sc">-</span> GLUCOSE<span class="sc">$</span>old</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Comprueba si puede asumirse la hipótesis de normalidad.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eda</span>(d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Practica3_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Size (n)  Missing  Minimum   1st Qu     Mean   Median   TrMean   3rd Qu 
  15.000    0.000    8.620   12.830   14.560   14.330   14.560   16.085 
     Max    Stdev      Var  SE Mean   I.Q.R.    Range Kurtosis Skewness 
  20.780    3.253   10.582    0.840    3.255   12.160   -0.677    0.105 
SW p-val 
   0.994 </code></pre>
</div>
</div>
<ul>
<li>Contrasta al nivel de significación <span class="math inline">\(\alpha=0.05\)</span> si el nuevo aparato proporciona mediciones más altas que el antiguo.</li>
</ul>
<p><span class="math display">\[\begin{eqnarray*}
H_0: \, \mu_D=0 \\
H_1: \, \mu_D&gt;0 \\
\end{eqnarray*}\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(d, <span class="at">mu=</span><span class="dv">0</span>, <span class="at">alternative=</span><span class="st">"greater"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  d
t = 17.335, df = 14, p-value = 3.701e-11
alternative hypothesis: true mean is greater than 0
95 percent confidence interval:
 13.08064      Inf
sample estimates:
mean of x 
    14.56 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># or</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(GLUCOSE<span class="sc">$</span>new, GLUCOSE<span class="sc">$</span>old, <span class="at">mu=</span><span class="dv">0</span>, <span class="at">paired=</span><span class="cn">TRUE</span>, <span class="at">alternative=</span><span class="st">"greater"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  GLUCOSE$new and GLUCOSE$old
t = 17.335, df = 14, p-value = 3.701e-11
alternative hypothesis: true mean difference is greater than 0
95 percent confidence interval:
 13.08064      Inf
sample estimates:
mean difference 
          14.56 </code></pre>
</div>
</div>
<p><strong>Interpretación</strong>: Como el p-valor<span class="math inline">\(\approx 0 &lt; \alpha=0.05 \Rightarrow\)</span> Rechazar <span class="math inline">\(H_0\)</span>.</p>
<p>Es decir, con un nivel de significación de 5%, existen evidencias estadísticas para afirmar que el nuevo aparato proporciona mediciones más altas (en media) que el antiguo.</p>
</section>
<section id="contrasta-al-nivel-de-significación-alpha0.05-si-la-proporción-de-hombres-con-hemoglobina-glicosilada-glyhb-por-encima-del-6-es-superior-a-0.2." class="level3">
<h3 class="anchored" data-anchor-id="contrasta-al-nivel-de-significación-alpha0.05-si-la-proporción-de-hombres-con-hemoglobina-glicosilada-glyhb-por-encima-del-6-es-superior-a-0.2.">1.5. Contrasta al nivel de significación <span class="math inline">\(\alpha=0.05\)</span> si la proporción de hombres con hemoglobina glicosilada (<code>glyhb</code>) por encima del 6% es superior a 0.2.</h3>
<ul>
<li>Calcula el número de hombres en la muestra con <code>glyhb</code> por encima del 6% y el total de hombre de la muestra.</li>
</ul>
<p>Definimos la variable <span class="math display">\[X=\mbox{"Número de hombres con hemoglobina glicosilada por encima del 6%"} \sim ~ Bin(n,\pi)\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Casos favorables ##</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">sum</span>(diabetes<span class="sc">$</span>gender<span class="sc">==</span><span class="st">"male"</span> <span class="sc">&amp;</span> diabetes<span class="sc">$</span>glyhb<span class="sc">&gt;</span><span class="dv">6</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 39</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Casos totales ##</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">sum</span>(diabetes<span class="sc">$</span>gender<span class="sc">==</span><span class="st">"male"</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>n</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 169</code></pre>
</div>
</div>
<ul>
<li>Realiza un test exacto y un test aproximado para la proporción. <span class="math display">\[\begin{eqnarray*}
H_0: \, \pi=0.2 \\
H_1: \, \pi&gt;0.2 \\
\end{eqnarray*}\]</span></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Test exacto </span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">binom.test</span>(x, n, <span class="at">p=</span><span class="fl">0.2</span>, <span class="at">alternative=</span><span class="st">"greater"</span>, <span class="at">conf.level=</span><span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact binomial test

data:  x and n
number of successes = 39, number of trials = 169, p-value = 0.182
alternative hypothesis: true probability of success is greater than 0.2
95 percent confidence interval:
 0.1783787 1.0000000
sample estimates:
probability of success 
             0.2307692 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Test aproximado</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(x, n, <span class="at">p=</span><span class="fl">0.2</span>, <span class="at">alternative=</span><span class="st">"greater"</span>, <span class="at">conf.level=</span><span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1-sample proportions test with continuity correction

data:  x out of n, null probability 0.2
X-squared = 0.81694, df = 1, p-value = 0.183
alternative hypothesis: true p is greater than 0.2
95 percent confidence interval:
 0.1792768 1.0000000
sample estimates:
        p 
0.2307692 </code></pre>
</div>
</div>
<p><strong>Interpretación</strong>: Como el p-valor&gt;<span class="math inline">\(\alpha=0.05 \Rightarrow\)</span> No rechazar <span class="math inline">\(H_0\)</span>.</p>
<p>Es decir, con un nivel de significación de 5%, no podemos afirmar que la proporción de hombres con hemoglobina glicosilada por encima del 6% sea superior a 0.2.</p>
</section>
<section id="contrasta-al-nivel-de-significación-alpha0.05-si-la-proporción-de-hombres-con-colesterol-por-debajo-de-200mgdl-es-superior-a-la-proporción-de-mujeres-con-colesterol-por-debajo-de-200mgdl." class="level3">
<h3 class="anchored" data-anchor-id="contrasta-al-nivel-de-significación-alpha0.05-si-la-proporción-de-hombres-con-colesterol-por-debajo-de-200mgdl-es-superior-a-la-proporción-de-mujeres-con-colesterol-por-debajo-de-200mgdl.">1.6. Contrasta al nivel de significación <span class="math inline">\(\alpha=0.05\)</span> si la proporción de hombres con colesterol por debajo de 200mg/dL es superior a la proporción de mujeres con colesterol por debajo de 200mg/dL.</h3>
<ul>
<li>Calcula el número de hombres en la muestra con colesterol por debajo de 200mg/dL y el total de hombres de la muestra.</li>
</ul>
<p>Sea <span class="math display">\[X=\mbox{"Número de hombres con colesterl por debajo de 200 mg/dL} \sim Bin(n_X,\pi_X)\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Casos favorables ##</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">sum</span>(diabetes<span class="sc">$</span>gender<span class="sc">==</span><span class="st">"male"</span> <span class="sc">&amp;</span> diabetes<span class="sc">$</span>chol<span class="sc">&lt;</span><span class="dv">200</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 79</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Casos totales ##</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>nx <span class="ot">&lt;-</span> <span class="fu">sum</span>(diabetes<span class="sc">$</span>gender<span class="sc">==</span><span class="st">"male"</span>)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>nx</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 169</code></pre>
</div>
</div>
<ul>
<li>Calcula el número de mujeres en la muestra con colesterol por debajo de 200mg/dL y el total de hombres de la muestra.</li>
</ul>
<p>Sea <span class="math display">\[Y=\mbox{"Número de mujeres con colesterol por debajo de 200 mg/dL} \sim Bin(n_Y,\pi_Y)\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Casos favorables ##</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">sum</span>(diabetes<span class="sc">$</span>gender<span class="sc">==</span><span class="st">"female"</span> <span class="sc">&amp;</span> diabetes<span class="sc">$</span>chol<span class="sc">&lt;</span><span class="dv">200</span>)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>y</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 105</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Casos totales ##</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>ny <span class="ot">&lt;-</span> <span class="fu">sum</span>(diabetes<span class="sc">$</span>gender<span class="sc">==</span><span class="st">"female"</span>)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>ny</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 234</code></pre>
</div>
</div>
<ul>
<li>Realiza un test para la diferencia de proporciones. <span class="math display">\[\begin{eqnarray*}
H_0: \, \pi_X-\pi_Y=0 \\
H_1: \, \pi_X-\pi_Y \neq 0 \\
\end{eqnarray*}\]</span></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="fu">c</span>(x,y), <span class="fu">c</span>(nx,ny), <span class="at">alternative=</span><span class="st">"greater"</span>, <span class="at">conf.level=</span><span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    2-sample test for equality of proportions with continuity correction

data:  c(x, y) out of c(nx, ny)
X-squared = 0.073608, df = 1, p-value = 0.3931
alternative hypothesis: greater
95 percent confidence interval:
 -0.06909495  1.00000000
sample estimates:
   prop 1    prop 2 
0.4674556 0.4487179 </code></pre>
</div>
</div>
<p><strong>Interpretación</strong>: Como el p-valor<span class="math inline">\(=0.393&gt;\alpha=0.05 \Rightarrow\)</span> No rechazar <span class="math inline">\(H_0\)</span>.</p>
<p>Es decir, con un nivel de significación de 5%, no podemos afirmar que la proporción de hombres con colesterol por debajo de 200mg/dL sea superior a la proporción de mujeres con colesterol por debajo de 200mg/dL.</p>
</section>
</section>
<section id="análisis-de-la-varianza" class="level1">
<h1>2. Análisis de la varianza</h1>
<section id="contrasta-al-nivel-de-significación-alpha0.10-si-el-tamaño-del-cuerpo-frame-influye-en-la-presión-diastólica-bp.1d-de-las-mujeres." class="level3">
<h3 class="anchored" data-anchor-id="contrasta-al-nivel-de-significación-alpha0.10-si-el-tamaño-del-cuerpo-frame-influye-en-la-presión-diastólica-bp.1d-de-las-mujeres.">2.1. Contrasta al nivel de significación <span class="math inline">\(\alpha=0.10\)</span> si el tamaño del cuerpo (<code>frame</code>) influye en la presión diastólica (<code>bp.1d</code>) de las mujeres.</h3>
<ul>
<li><p>Crea un nuevo fichero llamado <code>diabetes.female</code> solo con las mujeres.</p></li>
<li><p>Exploración gráfica: representa los diagrama de caja de la variable <code>bp.1d</code> según la variable <code>frame</code>.</p></li>
<li><p>Realiza el análisis de varianza con la función <code>aov()</code>.</p></li>
<li><p>Comprueba si pueden asumirse las hipótesis del modelo.</p></li>
<li><p>Utiliza un test de Tukey para averiguar entre qué niveles de la variable <code>frame</code> existen diferencias significativas en los niveles medios de la variable <code>bp.1d</code>.</p></li>
</ul>
</section>
</section>
<section id="para-entregar" class="level1">
<h1>3. Para entregar</h1>
<p>3.1. Contrasta al nivel de significación <span class="math inline">\(\alpha=0.10\)</span>, si la circunferencia de cadera media de los hombres es inferior a la circunferencia de cadera media de las mujeres.</p>
<ul>
<li><p>Comprueba si las dos muestras provienen de poblaciones normales.</p></li>
<li><p>Realiza el correspondiente test de medias.</p></li>
</ul>
<p>3.2. Se estudió la eficacia de la sulfinpirazona en prevenir la muerte después de sufrir infarto de miocardio. Para ello se consideraron pacientes que habían sufrido infarto de miocardio. A un grupo se les proporcionó sulfinpirazona y a otro grupo se les suministró placebo. En la siguiente tabla se muestra el número de pacientes de cada grupo que murieron y que superaron el infarto.</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>Death (all causes)</th>
<th>Survivors</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sulphinpyrazole</td>
<td>41</td>
<td>692</td>
</tr>
<tr class="even">
<td>Placebo</td>
<td>60</td>
<td>682</td>
</tr>
</tbody>
</table>
<p>Contrasta al nivel de significación <span class="math inline">\(\alpha=0.05\)</span> si la proporción de muertes de pacientes que tomaron sulfinpirazona es inferior a la de pacientes que tomaron un placebo.</p>
<p>3.3. Considera el fichero <code>diabetes</code>. Crea un nuevo fichero que contenga únicamente a las mujeres del condado de Louisa.</p>
<ul>
<li><p>Contrasta al nivel de significación <span class="math inline">\(\alpha=0.05\)</span> si existen diferencias entre los niveles medios de la variable <code>hdl</code> según la constitución del cuerpo <code>frame</code> en las mujeres del condado de Louisa.</p></li>
<li><p>Si has detectado diferencias, averigua entre qué grupos existen diferencias estadísticamente significativas.</p></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
      }
    }
});
</script>
</div> <!-- /content -->



</body></html>